name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install glsync
        run: |
          go install github.com/ahmed-e-abdulaziz/glsync@latest

      - name: Sync LeetCode
        env:
          LEETCODE_COOKIE: ${{ secrets.LEETCODE_SESSION }}
        run: |
          glsync \
            -lc-cookie="$LEETCODE_COOKIE" \
            -repo-url="https://github.com/${{ github.repository }}.git"
